apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: default
  annotations:
    # Flux will manage this container image using the ImagePolicy
    image.fluxcd.io/container.angular-helloworld: angular-app-policy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-helloworld
        image: shanudua/angular-app:latest   # Flux will auto-update this
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
  namespace: default
spec:
  selector:
    app: angular-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30083
  type: NodePort

